golden_words/articles/urls.py
from django.urls import path, include
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.article_detail, name='article'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('js_load_more/<int:from_>/<int:to>/', views.load_more),
    path('statistic/covid-19/', views.interesting, name='inetresting'),
    path('form/callback_form_ajax/', views.form, name='form'),
    path('api/articles/', views.api, name='api'),
    path('add_count_articles/<int:article_id>/', views.add_count_articles, name='add_count_articles'),
    path('parser_get_article_by_category/<str:category>/' , views.parser_get_article_by_category)

]

golden_words/golden_words/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from articles.models import Article

from django.contrib.sitemaps import Sitemap

info_dict = {
    'queryset': Article.objects.filter(status=True).order_by('-id'),
    'date_field': 'date',
}


class ArticleSitemap(Sitemap):
    changefreq = "daily"
    date_field = 'date'
    priority = 0.5

    def items(self):
        return Article.objects.filter(status=True).order_by('-id')

    def location(self, item):
        print(item)
        return reverse('articles:article', kwargs={
            'slug': item.slug
        })

    def lastmod(self, item):
        return item.date


urlpatterns = [

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('articles.urls', namespace='articles')),
    path('sitemap.xml', sitemap, {'sitemaps': {'blog': ArticleSitemap}},
         name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)
urlpatterns += [
]

golden_words/templates/includes/footer.html
{% load static %}
<footer>
    <div class="footer_container_top">
        <div class="footer_logo"><a href="{% url 'articles:home' %}">
            <img src="{% static 'images/golden_logo.png' %}" id="footer_logo" alt="Золоті слова"></a>
            <div class="footer_soc">

                <a href="https://t.me/zolotislova" class="tel"></a>
                <a href="https://www.facebook.com/%D0%97%D0%BE%D0%BB%D0%BE%D1%82%D1%96-%D1%81%D0%BB%D0%BE%D0%B2%D0%B0-103460374421454/?ref=br_rs" class="Fb">f</a>
                <a href="#" class="viber"></a>
            </div>
        </div>
        <div class="footer_container_bottom">
            <h6>© 2020 Золоті слова. Всі права захищено, повне або часткове копіювання матеріалів сайту без згоди з
                редакцією заборонено. Редакція може не погоджуватись із думкою авторів та не несе відповідальність за автентичність та достовірність матеріалів журнаістів</h6>
            <div class="footer_end">
                <h6 id="footer_autor">Дизайн та програмування </h6>
                <a href="https://avalan.studio/ua" class="Avalan">Avalan.studio</a>
            </div>
        </div>
     



        
</footer>

golden_words/templates/includes/header.html
{% load poll_extras %}
{% load mptt_tags %}
{% get_categories as category %}
{% privatbank as money %}
{% load static %}
<div class="help-line ">
    <div class="container help-container">
        <!--
                    <div id="enter" class="help-item w30">
                        увійти
                    </div>
        -->
        <div class="help-item w30">
        {% if  money %}


            <span>Курс валют:</span>
            {% for mon in money %}
            {% if mon.ccy == 'USD' %}
            $ - {{mon.buy|floatformat}} / {{mon.sale|floatformat}};
            {% elif mon.ccy == 'EUR' %}
            &euro; - {{mon.buy|floatformat}} / {{mon.sale|floatformat}}
            {% endif %}
            {% endfor %}
        {% endif %}
        </div>
        <!--
                    <div class="help-item " id="weather">
                        Погода на 3 дні
                    </div>
        -->
        <div class="help-item js-btn-form" id="writeUs">
            <div>Написати в редакцію</div>
            <span class="flug"></span>
        </div>
    </div>

    <div class="js-thx-popup thanks-text hide">
        <span id="close_thx">X</span>
        <p>Дякуємо що ви з нами!</p>
    </div>
</div>
<header class="">
    <div class="center-logo">
        <a href="{% url 'articles:home' %}" class="logo">
            <img src="{% static 'images/golden_logo.png' %}" alt="Золоті слова"></a>
    </div>
</header>

<nav class="desktop-nav nav-menu container">
    <a href="{% url 'articles:home' %}" class="logo" style="width: 220px;">
        <img src="{% static 'images/golden_logo.png' %}" alt="Золоті слова" style="max-width: 100%">
    </a>
    <div class="children_block">

        {% recursetree category.all_categories %}
        <div class="category-item {% if node.level == 0 %} arrow {% endif %}">

            <a {% if not node.is_leaf_node %}
               class=""
               {% endif %}
               href="{% if node.level != 0 %} {% url 'articles:category' node.slug %} {% else %}# {% endif %}">
                {{ node.name }}
                {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
                {% endif %}
            </a>
        </div>
        {% endrecursetree %}
        <div class="category-item">
            <a href="{% url 'articles:inetresting' %}">Статистика зараження</a>
        </div>
    </div>
</nav>


<nav class="mobile-nav nav-menu container">
    <a href="{% url 'articles:home' %}" class="logo" style="width: 220px;">
        <img src="{% static 'images/golden_logo.png' %}" alt="Золоті слова" style="max-width: 100%">
    </a>
    <div class="js-show-menu mobile-menu-btn">
        <span class="line-btn"></span>
        <span class="line-btn"></span>
        <span class="line-btn"></span>
    </div>
    <div class="mobile-children">

        {% recursetree category.all_categories %}
        <div class="{% if node.level == 0 %}js-mobile-drop arrow{% endif %}">
            {% if node.level == 0 %}
            <div {% if not node.is_leaf_node %}
                 class=""
                 {% endif %}
                 href="{% if node.level != 0 %} {% url 'articles:category' node.slug %} {% else %}{% endif %}">
                {{ node.name }}
                {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
                {% endif %}
            </div>

            {% else %}
            <a {% if not node.is_leaf_node %}
               class=""
               {% endif %}
               href="{% if node.level != 0 %} {% url 'articles:category' node.slug %} {% else %}{% endif %}">
                {{ node.name }}
                {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
                {% endif %}
            </a>
            {% endif %}
        </div>
        {% endrecursetree %}
        <div class="statCovid">
            <a href="{% url 'articles:inetresting' %}">Статистика зараження</a>
        </div>
        <div class="mobile_schow_block">
            <div class="write_redaktor js-btn-form">Написати в редакцію <span class="tel_icon"></span></div>
            <div class="words_text">© 2020 Золоті слова. Всі права захищено. Повне або часткове копіювання матеріалів
                сайту без згоди з редакцією заборонено.
            </div>
            <div class="programiring">Дизайн та програмування <a
                    href="https://avalan.studio/ua/ class">Avalan.studio</a></div>
        </div>
    </div>
</nav>


<div class="popup-wrap hide">
    <div class="form-wrap">
        <span class="js-close close">X</span>
        <form action="{% url 'articles:form' %}" id="callback_form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="">E-mail</label>
                <input type="email" name="email">
            </div>
            <div class="form-group">
                <label for="">Повiдомлення</label>
                <textarea name="msg" id="" cols="30" rows="10"></textarea>
            </div>
            <button class="submit-btn load-more">
                Отправить
            </button>
        </form>
    </div>
</div>